# Generated by ./configure -q
# Edit configure or re-run it; this file is overwritten.

_VERSION = 0.8-dev
VERSION  = `git describe --tags --dirty 2>/dev/null || echo $(_VERSION)`

CC = cc
PKG_CONFIG = pkg-config

# paths
PREFIX = /usr/local
BINDIR = $(HOME)/.local/bin
MANDIR = $(PREFIX)/share/man
DATADIR = $(PREFIX)/share

WLR_INCS = `$(PKG_CONFIG) --cflags wlroots-0.20`
WLR_LIBS = `$(PKG_CONFIG) --libs wlroots-0.20`

XWAYLAND = -DXWAYLAND
XLIBS = xcb xcb-icccm

BACKGROUND = -DINTEGRATED_BACKGROUND
BGLIBS = gdk-pixbuf-2.0

NOTIFY = -DNOTIFICATIONS

RUNNER = -DRUNNER

CFLAGS = -O2
LDFLAGS = 
LIBS = 
