# Generated by ./configure --compiler=clang --linker=mold --native
# Edit configure or re-run it; this file is overwritten.

_VERSION = 0.8-dev
VERSION  = `git describe --tags --dirty 2>/dev/null || echo $(_VERSION)`

CC = clang
PKG_CONFIG = pkg-config

# paths
PREFIX = /usr/local
BINDIR = $(HOME)/.local/bin
MANDIR = $(PREFIX)/share/man
DATADIR = $(PREFIX)/share

WLR_INCS = `$(PKG_CONFIG) --cflags wlroots-0.20`
WLR_LIBS = `$(PKG_CONFIG) --libs wlroots-0.20`

XWAYLAND = -DXWAYLAND
XLIBS = xcb xcb-icccm

BACKGROUND = -DINTEGRATED_BACKGROUND
BGLIBS = gdk-pixbuf-2.0

NOTIFY = -DNOTIFICATIONS

CFLAGS = -O3 -flto -march=native -mtune=native -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -fPIE -fcf-protection=full
LDFLAGS = -flto -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -fuse-ld=mold
LIBS = 
